#!/usr/bin/env bash
# DEPRECATED: calibrated scales are now the source defaults.
# Prefer: ./correctness/scripts/export_baseline_expected.sh [seed]
# Export Spike expected headers for the calibrated path (legacy USE_CALIBRATED name).
# Writes TAG=L{L}_D{D}_F{F}_seed{S}_cal to avoid clobbering non-calibrated snapshots.
# Usage: export_calibrated_expected.sh [seed]
set -euo pipefail

SEED=${1:-1}
D_MODEL=16
D_FF=64
ROOT=$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)
CHIPYARD=${CHIPYARD:-/home/users/ah072084/chipyard}
ROCC="$CHIPYARD/generators/gemmini/software/gemmini-rocc-tests"
OUT_DIR="$ROOT/correctness/expected"
LOG_DIR="$ROOT/correctness/logs"
mkdir -p "$OUT_DIR" "$LOG_DIR"

set +u
source "$CHIPYARD/env.sh"
set -u

for L in 16 32 64 128 256; do
  TAG="L${L}_D${D_MODEL}_F${D_FF}_seed${SEED}_cal"
  SNAP="$OUT_DIR/${TAG}.h"
  INC_DIR="$OUT_DIR/include_${TAG}"
  mkdir -p "$INC_DIR"
  CFLAGS="-DSEQ_LEN=$L -DD_MODEL=$D_MODEL -DD_FF=$D_FF -DPRNG_SEED=$SEED -DDUMP_EXPECTED=1"
  echo "[export-cal] $TAG"
  make -C "$ROCC/build/bareMetalC" -B \
    -f "$ROCC/bareMetalC/Makefile" \
    abs_top_srcdir="$ROCC" src_dir="$ROCC/bareMetalC" \
    XLEN=64 PREFIX=examples-bareMetalC \
    TRANSFORMER_CFLAGS="$CFLAGS" \
    transformer_block_test-baremetal >"$LOG_DIR/${TAG}.export_build.log" 2>&1
  spike --extension=gemmini "$ROCC/build/bareMetalC/transformer_block_test-baremetal" \
    |& tee "$LOG_DIR/${TAG}.export_spike.log" >/dev/null
  rg -qx PASS "$LOG_DIR/${TAG}.export_spike.log"

  python3 - "$LOG_DIR/${TAG}.export_spike.log" "$SNAP" "$L" "$D_MODEL" "$D_FF" "$SEED" <<'PY'
import sys
from pathlib import Path
log_path, out_path, L, D, F, seed = sys.argv[1:7]
L, D, F, seed = map(int, (L, D, F, seed))
text = Path(log_path).read_text().splitlines()
begin = next(i for i, line in enumerate(text) if line.startswith("BEGIN_EXPECTED"))
end = next(i for i, line in enumerate(text) if line.startswith("END_EXPECTED"))
rows = []
for line in text[begin + 1 : end]:
    if line.strip():
        rows.append([int(x) for x in line.split()])
if len(rows) != L or any(len(r) != D for r in rows):
    raise SystemExit(f"expected {L}x{D}, got {len(rows)} rows")
lines = [
    "/* Auto-generated by export_calibrated_expected.sh — do not hand-edit. */",
    f"/* SEQ_LEN={L} D_MODEL={D} D_FF={F} PRNG_SEED={seed} USE_CALIBRATED_QK_SCALES=1 */",
    "#ifndef TRANSFORMER_EXPECTED_H",
    "#define TRANSFORMER_EXPECTED_H",
    "#include <stdint.h>",
    f"static const int8_t expected_final[{L}][{D}] = {{",
]
for row in rows:
    lines.append("  {" + ", ".join(str(v) for v in row) + "},")
lines += ["};", "#endif", ""]
Path(out_path).write_text("\n".join(lines))
print(f"Wrote {out_path}")
PY
  cp "$SNAP" "$INC_DIR/transformer_expected.h"
  echo "Installed $INC_DIR/transformer_expected.h"
done
echo "Done exporting calibrated expected headers for seed=$SEED"
