#!/usr/bin/env bash
# Run Spike with float gold, then export final int8 as transformer_expected.h snapshot.
# Calibrated ACC_SCALE_Q/K / SCORE_DEQUANT / RMSNORM_GAIN are the source defaults.
# Usage: spike_export_expected.sh <L> <D_MODEL> <D_FF> [PRNG_SEED]
set -euo pipefail

if [[ $# -lt 3 || $# -gt 4 ]]; then
  echo "Usage: $0 <L> <D_MODEL> <D_FF> [PRNG_SEED]" >&2
  exit 2
fi

L=$1
D_MODEL=$2
D_FF=$3
SEED=${4:-1}

ROOT=$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)
CHIPYARD=${CHIPYARD:-/home/users/ah072084/chipyard}
ROCC="$CHIPYARD/generators/gemmini/software/gemmini-rocc-tests"
OUT_DIR="$ROOT/correctness/expected"
LOG_DIR="$ROOT/correctness/logs"
TAG="L${L}_D${D_MODEL}_F${D_FF}_seed${SEED}"
SNAP="$OUT_DIR/${TAG}.h"
INC_DIR="$OUT_DIR/include_${TAG}"
mkdir -p "$OUT_DIR" "$LOG_DIR" "$INC_DIR"

set +u
source "$CHIPYARD/env.sh"
set -u

echo "[export] Building Spike dump binary for $TAG"
make -C "$ROCC/build/bareMetalC" -B \
  -f "$ROCC/bareMetalC/Makefile" \
  abs_top_srcdir="$ROCC" src_dir="$ROCC/bareMetalC" \
  XLEN=64 PREFIX=examples-bareMetalC \
  TRANSFORMER_CFLAGS="-DSEQ_LEN=$L -DD_MODEL=$D_MODEL -DD_FF=$D_FF -DPRNG_SEED=$SEED -DDUMP_EXPECTED=1" \
  transformer_block_test-baremetal |& tee "$LOG_DIR/${TAG}.export_build.log"

spike --extension=gemmini \
  "$ROCC/build/bareMetalC/transformer_block_test-baremetal" \
  |& tee "$LOG_DIR/${TAG}.export_spike.log"

rg -qx PASS "$LOG_DIR/${TAG}.export_spike.log"

python3 - "$LOG_DIR/${TAG}.export_spike.log" "$SNAP" "$L" "$D_MODEL" "$D_FF" "$SEED" <<'PY'
import sys
from pathlib import Path

log_path, out_path, L, D, F, seed = sys.argv[1:7]
L, D, F, seed = map(int, (L, D, F, seed))
text = Path(log_path).read_text().splitlines()
try:
    begin = next(i for i, line in enumerate(text) if line.startswith("BEGIN_EXPECTED"))
    end = next(i for i, line in enumerate(text) if line.startswith("END_EXPECTED"))
except StopIteration as exc:
    raise SystemExit("BEGIN_EXPECTED/END_EXPECTED not found in Spike log") from exc

rows = []
for line in text[begin + 1 : end]:
    if not line.strip():
        continue
    rows.append([int(x) for x in line.split()])

if len(rows) != L or any(len(r) != D for r in rows):
    raise SystemExit(f"expected {L}x{D} ints, got {len(rows)} rows")

lines = [
    "/* Auto-generated by spike_export_expected.sh — do not hand-edit. */",
    f"/* SEQ_LEN={L} D_MODEL={D} D_FF={F} PRNG_SEED={seed} (calibrated baseline defaults) */",
    "#ifndef TRANSFORMER_EXPECTED_H",
    "#define TRANSFORMER_EXPECTED_H",
    "#include <stdint.h>",
    f"static const int8_t expected_final[{L}][{D}] = {{",
]
for row in rows:
    lines.append("  {" + ", ".join(str(v) for v in row) + "},")
lines += ["};", "#endif", ""]
Path(out_path).write_text("\n".join(lines))
print(f"Wrote {out_path}")
PY

# Convenience include name used by -DUSE_EXPECTED builds.
cp "$SNAP" "$INC_DIR/transformer_expected.h"
echo "[export] Snapshot: $SNAP"
echo "[export] Include dir for Verilator: $INC_DIR"
